#!/usr/bin/env bash

usage() {
  echo "Usage: ${0} <entity_name>"
}

for arg in "${@}"; do
  if [[ "${arg}" == "-h" || "${arg}" == "--help" ]]; then
    usage
    exit 0
  fi
done

if [[ ${#} -ne 1 ]]; then
  usage >&2
  exit 2
fi

entity_name="${1}"

ros2 service call /gzserver/delete_entity simulation_interfaces/srv/DeleteEntity "{
  entity: '${entity_name}'
}"
